apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager
type: Opaque
stringData:
  api-token: npnuIDxb7a8E3UqcAvgFN4on_BTg4CM5nHYvagFo # 粘贴 Token 到这里，不需要 base64 加密。