apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager
type: Opaque
stringData:
  api-token: i4MVxOd4o88Y8bHkDEHXAnJoytxhdaIiRzMaHWjk # 粘贴 Token 到这里，不需要 base64 加密。