apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: letsencrypt-prod-dns
  # namespace: default
spec:
  dnsNames:
  - httpserver-mesh.51.cafe
  issuerRef:
    group: cert-manager.io
    kind: Issuer
    name: letsencrypt-prod-dns
  secretName: letsencrypt-prod-dns # 最终签发出来的证书会保存在这个 Secret 里面
  acme:
    privateKeySecretRef:
      name: letsencrypt-prod-dns
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
    - dns01:
        ingress:
          class: nginx
        cloudflare:
          email: 865809599@qq.com # 替换成你的 cloudflare 邮箱账号，API Token 方式认证非必需，API Keys 认证是必需
          # apiTokenSecretRef:
          #   key: api-token
          #   name: cloudflare-api-token-secret # 引用保存 cloudflare 认证信息的 Secret
  # usages:
  # - digital signature
  # - key encipherment


# ---

# apiVersion: cert-manager.io/v1
# kind: ClusterIssuer
# metadata:
#   name: letsencrypt-dns01
# spec:
#   acme:
#     privateKeySecretRef:
#       name: letsencrypt-dns01
#     server: https://acme-v02.api.letsencrypt.org/directory
#     solvers:
#     - dns01:
#         cloudflare:
#           email: 865809599@qq.com # 替换成你的 cloudflare 邮箱账号，API Token 方式认证非必需，API Keys 认证是必需
#           # apiTokenSecretRef:
#           #   key: api-token
#           #   name: cloudflare-api-token-secret # 引用保存 cloudflare 认证信息的 Secret


# --- 
# apiVersion: cert-manager.io/v1
# kind: Certificate
# metadata:
#   name: test-mydomain-com
#   namespace: default
# spec:
#   dnsNames:
#   - test.mydomain.com # 要签发证书的域名
#   issuerRef:
#     kind: ClusterIssuer
#     name: letsencrypt-dns01 # 引用 ClusterIssuer，指示采用 dns01 方式进行校验
#   secretName: test-mydomain-com-tls # 最终签发出来的证书会保存在这个 Secret 里面


