apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc
  # name: datadir
  # namespace: stg1
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi