apiVersion: v1
kind: Pod
metadata:
  name: nginx-pv-pod
spec:
  volumes:
  - name: nginx-pv-storage
    persistentVolumeClaim:
      claimName: nfs-pvc
  containers:
  - name: nginx
    image: nginx
    ports:
    - name: http
      containerPort: 80
    volumeMounts:
    - name: nginx-pv-storage
      mountPath: /usr/share/nginx/html