apiVersion: v1
kind: Service
metadata: 
  labels:
    app: httpserver
  name: httpserver-svc
spec:
  ports:
    - port: 30001
      protocol: TCP
      targetPort: 80
  selector:
    app: httpserver
  type: LoadBalancer