apiVersion: v1
kind: Service
metadata: 
  annotations:
    prometheus.io/port: "8080"
    prometheus.io/scrape: "true"
  labels:
    app: httpserver
  name: httpserver-svc
spec:
  ports:
    - port: 30001
      protocol: TCP
      targetPort: 80
  selector:
    app: httpserver
  type: LoadBalancer